#!/bin/bash

export DISPLAY=:0.0

PASS=$(timeout 10 zenity --entry --title="Password OR kill!" --text="Password OR kill! You have 10 seconds!")

PIN="0000"

if [ "$PASS" -eq "$PIN" ]; then
   exit;
fi

H=$(date +%H)
if (( 1 <= 10#$H && 10#$H < 17 )); then
    # Between 1AM and 17PM
    qdbus org.freedesktop.ScreenSaver /ScreenSaver Lock
fi
