#!/bin/bash

PIN="0000" # Write your PIN code here

H=$(date +%H)
# Between 1AM and 17PM
if (( 1 <= 10#$H && 10#$H < 17 )); then
  export DISPLAY=:0.0 # Crontab needs this

  PASS=$(timeout 10 zenity --entry --title="Password OR kill!" --text="Password OR kill! You have 10 seconds!")

  if [ "$PASS" != "$PIN" ]; then
    # PIN does not match, lock the screen
    echo "LOCK"
    qdbus org.freedesktop.ScreenSaver /ScreenSaver Lock
  fi
fi
