#!/bin/bash
# Locks screen if user does not input right PIN code
# Supports KDE
# Crontab: */15 * * * * bash /usr/local/bin/screenlocktimer-zenity-bin

# If screen is already locked do nothing
if [[ $(ps -ef | grep -v grep | grep -c kscreenlocker_greet) -eq 1 ]]; then
  # kscreenlocker_greet process found!
  exit 1
fi

PIN="0000" # Write your PIN code here

H=$(date +%H)
# Between 1AM and 17PM
if (( 1 <= 10#$H && 10#$H < 17 )); then
  export DISPLAY=:0.0 # Crontab needs this

  # Locate your screen using
  # xrandr -q | grep " connected"
  xrandr --output DVI-I-1 --brightness 0.5

  PASS=$(timeout 10 zenity --entry --title="Password OR kill!" --text="Password OR kill! You have 10 seconds!")

  xrandr --output DVI-I-1 --brightness 1.0

  if [ "$PASS" != "$PIN" ]; then
    # PIN does not match, lock the screen
    qdbus org.freedesktop.ScreenSaver /ScreenSaver Lock
  fi
fi
